name: 'hdit_imagenet'

_target_: lavps.networks.load_hdit_epsilon_network
path: '/path/to/hdit-imagenet256-unconditional.pt'
fp16: false
network_kwargs:
  class_name: invfussion.models.hdit.HDiT
  joint: false
  in_mult: 1
  data: ImageNet256
  cfg_scale: 1
interface_kwargs:
  img_resolution: ${..image_resolution}
  img_channels: 3
  label_dim: 1000
  sigma_data: 0.5

image_resolution: 256
